# DrcomoMotionCast 全局设置文件

# 调试级别: DEBUG|INFO|NONE，可在运行时切换
debug: INFO

# 悬停检测配置
hover:
  min_ticks: 8               # 连续满足阈值的最小tick
  v_abs_y: 0.03              # 垂直速度阈值 |vy|
  h_speed: 0.06              # 水平速度阈值 sqrt(vx^2+vz^2)

# Tick调度器配置
tick:
  max_players_per_tick: 200  # 每帧处理玩家上限，超额分帧
